# IMPORTS

## Libraries

In [12]:
import pandas as pd
#import math
import numpy as np

import warnings
warnings.filterwarnings("ignore")

# import seaborn as sns

# import matplotlib.pyplot as plt
# from IPython.core.display import HTML

# from IPython.display import Image

## Helper Functions

In [2]:
# def jupyter_settings():
#     %matplotlib inline
#     %pylab inline
    
#     plt.style.use( 'bmh' )
#     plt.rcParams['figure.figsize'] = [25, 12]
#     plt.rcParams['font.size'] = 24
    
#     display( HTML( '<style>.container { width:100% !important; }</style>') )
#     pd.options.display.max_columns = None
#     pd.options.display.max_rows = None
#     pd.set_option( 'display.expand_frame_repr', False )
    
#     sns.set()

In [3]:
# jupyter_settings()

## Loading Data

In [7]:
dfRaw = pd.read_csv('../01-Data/Results/01-CRISPData/train.csv', low_memory=False, parse_dates=['Date'])

# FEATURE ENGINEERING

In [8]:
dfRaw1 = dfRaw.copy()

In [13]:
#year
dfRaw1['Year'] = dfRaw1['Date'].dt.year

#month
dfRaw1['Month'] = dfRaw1['Date'].dt.month

#day
dfRaw1['Day'] = dfRaw1['Date'].dt.day

#week of year
dfRaw1['WeekOfYear'] = dfRaw1['Date'].dt.weekofyear

#year week
dfRaw1['YearWeek'] = dfRaw1['Date'].dt.strftime('%Y-%W')

In [14]:
dfRaw1.head().T

,0,1,2,3,4
Store,1,2,3,4,5
DayOfWeek,5,5,5,5,5
Date,2015-07-31 00:00:00,2015-07-31 00:00:00,2015-07-31 00:00:00,2015-07-31 00:00:00,2015-07-31 00:00:00
Sales,5263,6064,8314,13995,4822
Customers,555,625,821,1498,559
Open,1,1,1,1,1
Promo,1,1,1,1,1
StateHoliday,0,0,0,0,0
SchoolHoliday,1,1,1,1,1
StoreType,c,a,a,c,a
Assortment,a,a,a,c,a
CompetitionDistance,1270,570,14130,620,29910
CompetitionOpenSinceMonth,9,11,12,9,4
CompetitionOpenSinceYear,2008,2007,2006,2009,2015
Promo2,0,1,1,0,0
Promo2SinceWeek,31,13,14,31,31
Promo2SinceYear,31,2010,2011,31,31
PromoInterval,0,"Jan,Apr,Jul,Oct","Jan,Apr,Jul,Oct",0,0
MonthMap,Jul,Jul,Jul,Jul,Jul
IsPromo,0,1,1,0,0
Year,2015,2015,2015,2015,2015
Month,7,7,7,7,7
Day,31,31,31,31,31
WeekOfYear,31,31,31,31,31
YearWeek,2015-30,2015-30,2015-30,2015-30,2015-30